use tests_subdir_layout::shout;
#[cfg(any(test, rudzio_test))]
#[allow(non_snake_case, reason = "generated by rudzio-migrate")]
#[::rudzio::suite(
    [(
        runtime = ::rudzio::runtime::tokio::Multithread::new,
        suite = ::rudzio::common::context::Suite,
        test = ::rudzio::common::context::Test,
    ),
    ]
)]
mod tests {
    use super::*;
    /* pre-migration (rudzio-migrate):
    #[test]
    fn shouts_loud() {
        assert_eq!(shout("hi"), "HI");
    }
    */
    #[::rudzio::test]
    async fn shouts_loud() -> ::anyhow::Result<()> {
        assert_eq!(shout("hi"), "HI");
        ::core::result::Result::Ok(())
    }
    /* pre-migration (rudzio-migrate):
    #[test]
    fn shouts_empty() {
        assert_eq!(shout(""), "");
    }
    */
    #[::rudzio::test]
    async fn shouts_empty() -> ::anyhow::Result<()> {
        assert_eq!(shout(""), "");
        ::core::result::Result::Ok(())
    }
}
