use existing_test_harness_flip::add;
#[cfg(test)]
#[allow(non_snake_case, reason = "generated by rudzio-migrate")]
#[::rudzio::suite(
    [(
        runtime = ::rudzio::runtime::tokio::Multithread::new,
        suite = ::rudzio::common::context::Suite,
        test = ::rudzio::common::context::Test,
    ),
    ]
)]
mod tests {
    use super::*;
    use ::rudzio::common::context::Test;
    /* pre-migration (rudzio-migrate):
    #[test]
    fn sums() {
        assert_eq!(add(1, 2), 3);
    }
    */
    #[::rudzio::test]
    async fn sums(_ctx: &Test) -> ::anyhow::Result<()> {
        assert_eq!(add(1, 2), 3);
        ::core::result::Result::Ok(())
    }
}
#[::rudzio::main]
fn main() {}
