use test_context::TestContext;
pub struct FileCtx {
    pub path: String,
}
impl TestContext for FileCtx {
    fn setup() -> Self {
        FileCtx {
            path: "/tmp/test.txt".to_owned(),
        }
    }
    fn teardown(self) {
        let _ = self.path;
    }
}
#[cfg(any(test, rudzio_test))]

/// Generated by rudzio-migrate: bridge wrapper for `FileCtx`. Takes the
/// `<'test_context, R>` generics rudzio's `#[rudzio::test]` macro
/// injects into ctx-param types, while the inner field is still your
/// original `FileCtx` (field access works via `Deref`/`DerefMut`).
pub struct FileCtxRudzioBridge<'test_context, R>
where
    R: ::rudzio::Runtime<'test_context> + ::core::marker::Sync,
{
    pub inner: FileCtx,
    _marker: ::core::marker::PhantomData<&'test_context R>,
}

impl<'test_context, R> ::core::ops::Deref for FileCtxRudzioBridge<'test_context, R>
where
    R: ::rudzio::Runtime<'test_context> + ::core::marker::Sync,
{
    type Target = FileCtx;
    fn deref(&self) -> &FileCtx { &self.inner }
}

impl<'test_context, R> ::core::ops::DerefMut for FileCtxRudzioBridge<'test_context, R>
where
    R: ::rudzio::Runtime<'test_context> + ::core::marker::Sync,
{
    fn deref_mut(&mut self) -> &mut FileCtx { &mut self.inner }
}

impl<'test_context, R> ::core::fmt::Debug for FileCtxRudzioBridge<'test_context, R>
where
    R: ::rudzio::Runtime<'test_context> + ::core::marker::Sync,
{
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("FileCtxRudzioBridge").finish_non_exhaustive()
    }
}

/// Generated by rudzio-migrate: bridge suite type so
/// `#[rudzio::suite([...])]` can reference a concrete Suite impl that
/// resolves to the `FileCtxRudzioBridge` wrapper for each test. The generics
/// mirror what rudzio's `#[rudzio::suite(...)]` attribute expects: a
/// lifetime and a `Runtime`-bounded type parameter, both injected
/// invisibly at the callsite.
pub struct FileCtxRudzioSuite<'suite_context, R>
where
    R: for<'__r> ::rudzio::Runtime<'__r> + ::core::marker::Sync,
{
    _marker: ::core::marker::PhantomData<&'suite_context R>,
}

impl<'suite_context, R> ::core::fmt::Debug for FileCtxRudzioSuite<'suite_context, R>
where
    R: for<'__r> ::rudzio::Runtime<'__r> + ::core::marker::Sync,
{
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("FileCtxRudzioSuite").finish_non_exhaustive()
    }
}

impl<'suite_context, R> ::rudzio::Suite<'suite_context, R> for FileCtxRudzioSuite<'suite_context, R>
where
    R: for<'__r> ::rudzio::Runtime<'__r> + ::core::marker::Sync,
{
    type ContextError = ::rudzio::BoxError;
    type SetupError = ::rudzio::BoxError;
    type TeardownError = ::rudzio::BoxError;

    type Test<'test_context>
        = FileCtxRudzioBridge<'test_context, R>
    where
        Self: 'test_context;

    fn setup(
        _runtime: &'suite_context R,
        _cancel: ::rudzio::tokio_util::sync::CancellationToken,
        _config: &'suite_context ::rudzio::Config,
    ) -> impl ::core::future::Future<Output = ::core::result::Result<Self, Self::SetupError>>
        + ::core::marker::Send
        + 'suite_context {
        async move {
            ::core::result::Result::Ok(FileCtxRudzioSuite { _marker: ::core::marker::PhantomData })
        }
    }

    fn context<'test_context>(
        &'test_context self,
        _cancel: ::rudzio::tokio_util::sync::CancellationToken,
        _config: &'test_context ::rudzio::Config,
    ) -> impl ::core::future::Future<
        Output = ::core::result::Result<FileCtxRudzioBridge<'test_context, R>, Self::ContextError>,
    > + ::core::marker::Send
       + 'test_context {
        async move {
            ::core::result::Result::Ok(FileCtxRudzioBridge {
                inner: <FileCtx as ::test_context::TestContext>::setup(),
                _marker: ::core::marker::PhantomData,
            })
        }
    }

    fn teardown(
        self,
    ) -> impl ::core::future::Future<Output = ::core::result::Result<(), Self::TeardownError>>
        + ::core::marker::Send
        + 'suite_context {
        async move { ::core::result::Result::Ok(()) }
    }
}

impl<'test_context, R> ::rudzio::Test<'test_context, R> for FileCtxRudzioBridge<'test_context, R>
where
    R: ::rudzio::Runtime<'test_context> + ::core::marker::Sync,
{
    type TeardownError = ::rudzio::BoxError;

    fn teardown(
        self,
    ) -> impl ::core::future::Future<Output = ::core::result::Result<(), Self::TeardownError>>
        + ::core::marker::Send
        + 'test_context {
        async move {
            <FileCtx as ::test_context::TestContext>::teardown(self.inner);
            ::core::result::Result::Ok(())
        }
    }
}
#[::rudzio::suite(
    [(
        runtime = ::rudzio::runtime::tokio::Multithread::new,
        suite = crate::FileCtxRudzioSuite,
        test = crate::FileCtxRudzioBridge,
    ),
    ]
)]
mod tests {
    use super::*;
    /* pre-migration (rudzio-migrate):
    #[test_context(FileCtx)]
    #[test]
    fn reads_path(ctx: &mut FileCtx) {
        assert!(!ctx.path.is_empty());
    }
    */
    #[::rudzio::test]
    async fn reads_path(ctx: &mut FileCtxRudzioBridge) {
        assert!(! ctx.path.is_empty());
    }
}
#[cfg(test)]
#[::rudzio::main]
fn main() {}
