use test_context::AsyncTestContext;

pub struct DeepCtx {
    pub depth: u32,
}

impl AsyncTestContext for DeepCtx {
    async fn setup() -> Self {
        DeepCtx { depth: 0 }
    }

    async fn teardown(self) {
        let _ = self.depth;
    }
}

/// Generated by rudzio-migrate: bridge wrapper for `DeepCtx`. Takes the
/// `<'test_context, R>` generics rudzio's `#[rudzio::test]` macro
/// injects into ctx-param types, while the inner field is still your
/// original `DeepCtx` (field access works via `Deref`/`DerefMut`).
pub struct DeepCtxRudzioBridge<'test_context, R>
where
    R: ::rudzio::Runtime<'test_context> + ::core::marker::Sync,
{
    pub inner: DeepCtx,
    _marker: ::core::marker::PhantomData<&'test_context R>,
}

impl<'test_context, R> ::core::ops::Deref for DeepCtxRudzioBridge<'test_context, R>
where
    R: ::rudzio::Runtime<'test_context> + ::core::marker::Sync,
{
    type Target = DeepCtx;
    fn deref(&self) -> &DeepCtx { &self.inner }
}

impl<'test_context, R> ::core::ops::DerefMut for DeepCtxRudzioBridge<'test_context, R>
where
    R: ::rudzio::Runtime<'test_context> + ::core::marker::Sync,
{
    fn deref_mut(&mut self) -> &mut DeepCtx { &mut self.inner }
}

impl<'test_context, R> ::core::fmt::Debug for DeepCtxRudzioBridge<'test_context, R>
where
    R: ::rudzio::Runtime<'test_context> + ::core::marker::Sync,
{
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("DeepCtxRudzioBridge").finish_non_exhaustive()
    }
}

/// Generated by rudzio-migrate: bridge suite type so
/// `#[rudzio::suite([...])]` can reference a concrete Suite impl that
/// resolves to the `DeepCtxRudzioBridge` wrapper for each test. The generics
/// mirror what rudzio's `#[rudzio::suite(...)]` attribute expects: a
/// lifetime and a `Runtime`-bounded type parameter, both injected
/// invisibly at the callsite.
pub struct DeepCtxRudzioSuite<'suite_context, R>
where
    R: for<'__r> ::rudzio::Runtime<'__r> + ::core::marker::Sync,
{
    _marker: ::core::marker::PhantomData<&'suite_context R>,
}

impl<'suite_context, R> ::core::fmt::Debug for DeepCtxRudzioSuite<'suite_context, R>
where
    R: for<'__r> ::rudzio::Runtime<'__r> + ::core::marker::Sync,
{
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("DeepCtxRudzioSuite").finish_non_exhaustive()
    }
}

impl<'suite_context, R> ::rudzio::Suite<'suite_context, R> for DeepCtxRudzioSuite<'suite_context, R>
where
    R: for<'__r> ::rudzio::Runtime<'__r> + ::core::marker::Sync,
{
    type ContextError = ::rudzio::BoxError;
    type SetupError = ::rudzio::BoxError;
    type TeardownError = ::rudzio::BoxError;

    type Test<'test_context>
        = DeepCtxRudzioBridge<'test_context, R>
    where
        Self: 'test_context;

    fn setup(
        _runtime: &'suite_context R,
        _cancel: ::rudzio::tokio_util::sync::CancellationToken,
        _config: &'suite_context ::rudzio::Config,
    ) -> impl ::core::future::Future<Output = ::core::result::Result<Self, Self::SetupError>>
        + ::core::marker::Send
        + 'suite_context {
        async move {
            ::core::result::Result::Ok(DeepCtxRudzioSuite { _marker: ::core::marker::PhantomData })
        }
    }

    fn context<'test_context>(
        &'test_context self,
        _cancel: ::rudzio::tokio_util::sync::CancellationToken,
        _config: &'test_context ::rudzio::Config,
    ) -> impl ::core::future::Future<
        Output = ::core::result::Result<DeepCtxRudzioBridge<'test_context, R>, Self::ContextError>,
    > + ::core::marker::Send
       + 'test_context {
        async move {
            ::core::result::Result::Ok(DeepCtxRudzioBridge {
                inner: <DeepCtx as ::test_context::AsyncTestContext>::setup().await,
                _marker: ::core::marker::PhantomData,
            })
        }
    }

    fn teardown(
        self,
    ) -> impl ::core::future::Future<Output = ::core::result::Result<(), Self::TeardownError>>
        + ::core::marker::Send
        + 'suite_context {
        async move { ::core::result::Result::Ok(()) }
    }
}

impl<'test_context, R> ::rudzio::Test<'test_context, R> for DeepCtxRudzioBridge<'test_context, R>
where
    R: ::rudzio::Runtime<'test_context> + ::core::marker::Sync,
{
    type TeardownError = ::rudzio::BoxError;

    fn teardown(
        self,
    ) -> impl ::core::future::Future<Output = ::core::result::Result<(), Self::TeardownError>>
        + ::core::marker::Send
        + 'test_context {
        async move {
            <DeepCtx as ::test_context::AsyncTestContext>::teardown(self.inner).await;
            ::core::result::Result::Ok(())
        }
    }
}
