//! Shared-runner scaffolding: create or append `tests/main.rs` with
//! a `#[rudzio::main] fn main() {}` entry.
//!
//! v1 behaviour: create `tests/main.rs` only when it doesn't exist. If
//! it does exist, emit a warning and leave it alone — touching the
//! user's existing main is too invasive for a best-effort tool.

use std::fs;
use std::path::Path;

use anyhow::{Context as _, Result};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ScaffoldOutcome {
    Created,
    AlreadyExists,
}

pub fn ensure_tests_main(
    tests_main_path: &Path,
    crate_lib_name: Option<&str>,
) -> Result<ScaffoldOutcome> {
    if tests_main_path.exists() {
        return Ok(ScaffoldOutcome::AlreadyExists);
    }
    if let Some(parent) = tests_main_path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
    }
    let content = render_template(crate_lib_name);
    fs::write(tests_main_path, content)
        .with_context(|| format!("writing {}", tests_main_path.display()))?;
    Ok(ScaffoldOutcome::Created)
}

fn render_template(crate_lib_name: Option<&str>) -> String {
    // The `use <crate> as _;` line keeps the integration test binary
    // from stripping the lib's rlib during link, so any
    // `linkme::distributed_slice` entries the lib registers at its
    // non-test scope survive. Suite blocks under `#[cfg(test)]`
    // inside the lib aren't visible in this build — they need
    // `#[path]` aggregation + module re-exports to run from here,
    // which the tool doesn't emit automatically in v1. The
    // integration tests under `tests/*.rs` are the primary workload.
    let crate_use = match crate_lib_name {
        Some(name) => format!("use {name} as _;\n\n"),
        None => String::new(),
    };
    format!(
        "\
//! Rudzio test runner entry. Generated by rudzio-migrate.
//!
//! All `#[rudzio::suite(...)]` blocks registered at the lib's
//! non-test scope reach this binary via the `use <crate> as _;`
//! below. Suite blocks gated by `#[cfg(test)]` inside the lib
//! don't — they require `#[path]` aggregation here with the lib's
//! `crate::<mod>::...` paths re-exported.

{crate_use}#[rudzio::main]
fn main() {{}}
"
    )
}
