//! Shared-runner scaffolding: create or append `tests/main.rs` with
//! a `#[rudzio::main] fn main() {}` entry.
//!
//! v1 behaviour: create `tests/main.rs` only when it doesn't exist. If
//! it does exist, emit a warning and leave it alone — touching the
//! user's existing main is too invasive for a best-effort tool.

use std::fs;
use std::path::Path;

use anyhow::{Context as _, Result};

pub enum ScaffoldOutcome {
    Created,
    AlreadyExists,
}

pub fn ensure_tests_main(
    tests_main_path: &Path,
    crate_lib_name: Option<&str>,
) -> Result<ScaffoldOutcome> {
    if tests_main_path.exists() {
        return Ok(ScaffoldOutcome::AlreadyExists);
    }
    if let Some(parent) = tests_main_path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
    }
    let content = render_template(crate_lib_name);
    fs::write(tests_main_path, content)
        .with_context(|| format!("writing {}", tests_main_path.display()))?;
    Ok(ScaffoldOutcome::Created)
}

fn render_template(crate_lib_name: Option<&str>) -> String {
    // The `use <crate> as _;` line is load-bearing: without at least one
    // reference to the lib crate, the integration test binary's linker
    // will drop the rlib and every `linkme::distributed_slice` entry
    // registered inside it — producing a runner that sees zero tests.
    let crate_use = match crate_lib_name {
        Some(name) => format!("use {name} as _;\n\n"),
        None => String::new(),
    };
    format!(
        "\
//! Rudzio test runner entry. Generated by rudzio-migrate.
//!
//! All `#[rudzio::suite(...)]` blocks in this crate register their
//! tests into a `linkme` distributed slice at compile time; this file
//! only has to exist, provide the `#[rudzio::main]` entry, and reference
//! the lib crate so the linker keeps those registrations alive.

{crate_use}#[rudzio::main]
fn main() {{}}
"
    )
}
