//! Golden-test harness for rudzio-migrate.
#![allow(
    clippy::panic,
    clippy::panic_in_result_fn,
    clippy::expect_used,
    clippy::format_push_string,
    clippy::branches_sharing_code,
    clippy::manual_assert,
    reason = "test harness: panic-on-diff and Result-shaped helpers are intentional"
)]
//!
//! Each fixture directory under `migrate/fixtures/<scenario>/` has an
//! `input/` tree (a minimal Rust package as it would exist before
//! migration) and an `expected/` tree (same package in the shape the
//! tool is expected to produce). The harness copies `input/` to a
//! tempdir, initialises it as a git repo, runs the binary with the
//! acknowledgement phrase piped via stdin, and diffs the result
//! against `expected/` byte-for-byte.
//!
//! `args.txt` (optional) provides extra CLI args; the first line is
//! parsed whitespace-split. `stdin.txt` (optional) overrides the
//! default stdin script (ACK phrase + "n" to skip the shared-runner
//! scaffolding). Scenario dirs without either file use the defaults.
use std::fs;
use std::io::Write as _;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
const ACK_PHRASE: &str = "I am not and idion and understand what I am doing in most cases at least";
#[cfg(test)]
#[allow(non_snake_case, reason = "generated by rudzio-migrate")]
#[::rudzio::suite(
    [(
        runtime = ::rudzio::runtime::tokio::Multithread::new,
        suite = ::rudzio::common::context::Suite,
        test = ::rudzio::common::context::Test,
    ),
    ]
)]
mod tests {
    use ::rudzio::common::context::Test;
    use super::*;
    /* pre-migration (rudzio-migrate):
    #[test]
    fn golden_plain_sync_test() {
        run_fixture("plain_sync_test");
    }
    */
    #[::rudzio::test]
    async fn golden_plain_sync_test(_ctx: &Test) -> ::anyhow::Result<()> {
        run_fixture("plain_sync_test");
        ::core::result::Result::Ok(())
    }
    /* pre-migration (rudzio-migrate):
    #[test]
    fn golden_test_context_migration() {
        run_fixture("test_context_migration");
    }
    */
    #[::rudzio::test]
    async fn golden_test_context_migration(_ctx: &Test) -> ::anyhow::Result<()> {
        run_fixture("test_context_migration");
        ::core::result::Result::Ok(())
    }
    /* pre-migration (rudzio-migrate):
    #[test]
    fn golden_tokio_default() {
        run_fixture("tokio_default");
    }
    */
    #[::rudzio::test]
    async fn golden_tokio_default(_ctx: &Test) -> ::anyhow::Result<()> {
        run_fixture("tokio_default");
        ::core::result::Result::Ok(())
    }
    /* pre-migration (rudzio-migrate):
    #[test]
    fn golden_tokio_multi_thread() {
        run_fixture("tokio_multi_thread");
    }
    */
    #[::rudzio::test]
    async fn golden_tokio_multi_thread(_ctx: &Test) -> ::anyhow::Result<()> {
        run_fixture("tokio_multi_thread");
        ::core::result::Result::Ok(())
    }
    /* pre-migration (rudzio-migrate):
    #[test]
    fn golden_tokio_current_thread() {
        run_fixture("tokio_current_thread");
    }
    */
    #[::rudzio::test]
    async fn golden_tokio_current_thread(_ctx: &Test) -> ::anyhow::Result<()> {
        run_fixture("tokio_current_thread");
        ::core::result::Result::Ok(())
    }
    /* pre-migration (rudzio-migrate):
    #[test]
    fn golden_ignore_variants() {
        run_fixture("ignore_variants");
    }
    */
    #[::rudzio::test]
    async fn golden_ignore_variants(_ctx: &Test) -> ::anyhow::Result<()> {
        run_fixture("ignore_variants");
        ::core::result::Result::Ok(())
    }
    /* pre-migration (rudzio-migrate):
    #[test]
    fn golden_should_panic_warn() {
        run_fixture("should_panic_warn");
    }
    */
    #[::rudzio::test]
    async fn golden_should_panic_warn(_ctx: &Test) -> ::anyhow::Result<()> {
        run_fixture("should_panic_warn");
        ::core::result::Result::Ok(())
    }
    /* pre-migration (rudzio-migrate):
    #[test]
    fn golden_bench_warn() {
        run_fixture("bench_warn");
    }
    */
    #[::rudzio::test]
    async fn golden_bench_warn(_ctx: &Test) -> ::anyhow::Result<()> {
        run_fixture("bench_warn");
        ::core::result::Result::Ok(())
    }
    /* pre-migration (rudzio-migrate):
    #[test]
    fn golden_rstest_skipped() {
        run_fixture("rstest_skipped");
    }
    */
    #[::rudzio::test]
    async fn golden_rstest_skipped(_ctx: &Test) -> ::anyhow::Result<()> {
        run_fixture("rstest_skipped");
        ::core::result::Result::Ok(())
    }
    #[::rudzio::test]
    async fn golden_plain_async_test(_ctx: &Test) -> ::anyhow::Result<()> {
        run_fixture("plain_async_test");
        ::core::result::Result::Ok(())
    }
    #[::rudzio::test]
    async fn golden_async_std_test(_ctx: &Test) -> ::anyhow::Result<()> {
        run_fixture("async_std_test");
        ::core::result::Result::Ok(())
    }
    #[::rudzio::test]
    async fn golden_compio_test(_ctx: &Test) -> ::anyhow::Result<()> {
        run_fixture("compio_test");
        ::core::result::Result::Ok(())
    }
    #[::rudzio::test]
    async fn golden_result_returning_test(_ctx: &Test) -> ::anyhow::Result<()> {
        run_fixture("result_returning_test");
        ::core::result::Result::Ok(())
    }
    #[::rudzio::test]
    async fn golden_dry_run(_ctx: &Test) -> ::anyhow::Result<()> {
        run_fixture("dry_run");
        ::core::result::Result::Ok(())
    }
    #[::rudzio::test]
    async fn golden_no_shared_runner_flag(_ctx: &Test) -> ::anyhow::Result<()> {
        run_fixture("no_shared_runner_flag");
        ::core::result::Result::Ok(())
    }
    #[::rudzio::test]
    async fn golden_no_preserve_originals_flag(_ctx: &Test) -> ::anyhow::Result<()> {
        run_fixture("no_preserve_originals_flag");
        ::core::result::Result::Ok(())
    }
    #[::rudzio::test]
    async fn golden_nested_modules(_ctx: &Test) -> ::anyhow::Result<()> {
        run_fixture("nested_modules");
        ::core::result::Result::Ok(())
    }
    #[::rudzio::test]
    async fn golden_integration_file(_ctx: &Test) -> ::anyhow::Result<()> {
        run_fixture("integration_file");
        ::core::result::Result::Ok(())
    }
    #[::rudzio::test]
    async fn golden_test_context_sync_variant(_ctx: &Test) -> ::anyhow::Result<()> {
        run_fixture("test_context_sync_variant");
        ::core::result::Result::Ok(())
    }
    #[::rudzio::test]
    async fn golden_test_context_unresolvable(_ctx: &Test) -> ::anyhow::Result<()> {
        run_fixture("test_context_unresolvable");
        ::core::result::Result::Ok(())
    }
    #[::rudzio::test]
    async fn golden_workspace_crate(_ctx: &Test) -> ::anyhow::Result<()> {
        run_fixture("workspace_crate");
        ::core::result::Result::Ok(())
    }
    #[::rudzio::test]
    async fn golden_result_returning_block_body(_ctx: &Test) -> ::anyhow::Result<()> {
        run_fixture("result_returning_block_body");
        ::core::result::Result::Ok(())
    }
    #[::rudzio::test]
    async fn golden_tests_only_flag(_ctx: &Test) -> ::anyhow::Result<()> {
        run_fixture("tests_only_flag");
        ::core::result::Result::Ok(())
    }
    #[::rudzio::test]
    async fn golden_existing_test_harness_flip(_ctx: &Test) -> ::anyhow::Result<()> {
        run_fixture("existing_test_harness_flip");
        ::core::result::Result::Ok(())
    }
    #[::rudzio::test]
    async fn golden_tests_subdir_layout(_ctx: &Test) -> ::anyhow::Result<()> {
        run_fixture("tests_subdir_layout");
        ::core::result::Result::Ok(())
    }
    #[::rudzio::test]
    async fn golden_test_context_nested_impl(_ctx: &Test) -> ::anyhow::Result<()> {
        run_fixture("test_context_nested_impl");
        ::core::result::Result::Ok(())
    }
    #[::rudzio::test]
    async fn golden_ambassador_verbatim(_ctx: &Test) -> ::anyhow::Result<()> {
        run_fixture("ambassador_verbatim");
        ::core::result::Result::Ok(())
    }
    #[::rudzio::test]
    async fn golden_ambassador_verbatim_with_tests(_ctx: &Test) -> ::anyhow::Result<()> {
        run_fixture("ambassador_verbatim_with_tests");
        ::core::result::Result::Ok(())
    }
    #[::rudzio::test]
    async fn golden_cfg_test_with_expect_attr(_ctx: &Test) -> ::anyhow::Result<()> {
        run_fixture("cfg_test_with_expect_attr");
        ::core::result::Result::Ok(())
    }
    #[::rudzio::test]
    async fn golden_lib_unit_tests_harness_false(_ctx: &Test) -> ::anyhow::Result<()> {
        run_fixture("lib_unit_tests_harness_false");
        ::core::result::Result::Ok(())
    }
    #[::rudzio::test]
    async fn golden_nested_parent_mod_not_promoted(_ctx: &Test) -> ::anyhow::Result<()> {
        run_fixture("nested_parent_mod_not_promoted");
        ::core::result::Result::Ok(())
    }
    /* pre-migration (rudzio-migrate):
    #[test]
    fn golden_dirty_tree_refusal() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path();
        setup_minimal_lib_crate(path, "dirty_tree").expect("setup");
        git_init_commit(path).expect("git commit");
        // Make the tree dirty *after* the commit so the tool sees
        // uncommitted changes.
        fs::write(path.join("src/lib.rs"), b"// uncommitted edit\n")
            .expect("dirty write");

        let output = run_migrate(path, &["--dry-run"], "").expect("spawn");
        assert_eq!(
            output.status.code(),
            Some(1_i32),
            "expected exit 1 for dirty tree; got {:?}\nstdout:\n{}\nstderr:\n{}",
            output.status,
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr),
        );
        let stdout = String::from_utf8_lossy(&output.stdout);
        assert!(
            stdout.contains("refusing to run because the working tree has uncommitted changes"),
            "expected dirty-tree disclaimer; got:\n{stdout}"
        );
        assert!(
            stdout.contains("This tool is not going to do any magic"),
            "expected best-effort disclaimer; got:\n{stdout}"
        );
        // Nothing must have been written — the whole point of the gate.
        assert!(
            !path.join("src/lib.rs.backup_before_migration_to_rudzio").exists(),
            "backup should not have been created for a dirty tree refusal",
        );
    }
    */
    #[::rudzio::test]
    async fn golden_dirty_tree_refusal(_ctx: &Test) -> ::anyhow::Result<()> {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path();
        setup_minimal_lib_crate(path, "dirty_tree").expect("setup");
        git_init_commit(path).expect("git commit");
        fs::write(path.join("src/lib.rs"), b"// uncommitted edit\n")
            .expect("dirty write");
        let output = run_migrate(path, &["--dry-run"], "").expect("spawn");
        assert_eq!(
            output.status.code(), Some(1_i32),
            "expected exit 1 for dirty tree; got {:?}\nstdout:\n{}\nstderr:\n{}", output
            .status, String::from_utf8_lossy(& output.stdout), String::from_utf8_lossy(&
            output.stderr),
        );
        let stdout = String::from_utf8_lossy(&output.stdout);
        assert!(
            stdout
            .contains("refusing to run because the working tree has uncommitted changes"),
            "expected dirty-tree disclaimer; got:\n{stdout}"
        );
        assert!(
            stdout.contains("This tool is not going to do any magic"),
            "expected best-effort disclaimer; got:\n{stdout}"
        );
        assert!(
            ! path.join("src/lib.rs.backup_before_migration_to_rudzio").exists(),
            "backup should not have been created for a dirty tree refusal",
        );
        ::core::result::Result::Ok(())
    }
    /* pre-migration (rudzio-migrate):
    #[test]
    fn golden_wrong_acknowledgement() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path();
        setup_minimal_lib_crate(path, "wrong_ack").expect("setup");
        git_init_commit(path).expect("git commit");

        // A subtly-different phrase: corrected typo + "an" instead of "and".
        let wrong = "I am not an idiot and understand what I am doing in most cases at least\n";
        let output = run_migrate(path, &[], wrong).expect("spawn");
        assert_eq!(
            output.status.code(),
            Some(1_i32),
            "expected exit 1 for wrong ack; got {:?}\nstdout:\n{}\nstderr:\n{}",
            output.status,
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr),
        );
        let stdout = String::from_utf8_lossy(&output.stdout);
        assert!(
            stdout.contains("acknowledgement did not match"),
            "expected ack-mismatch abort message; got:\n{stdout}"
        );
        assert!(
            !path.join("src/lib.rs.backup_before_migration_to_rudzio").exists(),
            "backup should not have been created for a wrong ack",
        );
    }
    */
    #[::rudzio::test]
    async fn golden_wrong_acknowledgement(_ctx: &Test) -> ::anyhow::Result<()> {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path();
        setup_minimal_lib_crate(path, "wrong_ack").expect("setup");
        git_init_commit(path).expect("git commit");
        let wrong = "I am not an idiot and understand what I am doing in most cases at least\n";
        let output = run_migrate(path, &[], wrong).expect("spawn");
        assert_eq!(
            output.status.code(), Some(1_i32),
            "expected exit 1 for wrong ack; got {:?}\nstdout:\n{}\nstderr:\n{}", output
            .status, String::from_utf8_lossy(& output.stdout), String::from_utf8_lossy(&
            output.stderr),
        );
        let stdout = String::from_utf8_lossy(&output.stdout);
        assert!(
            stdout.contains("acknowledgement did not match"),
            "expected ack-mismatch abort message; got:\n{stdout}"
        );
        assert!(
            ! path.join("src/lib.rs.backup_before_migration_to_rudzio").exists(),
            "backup should not have been created for a wrong ack",
        );
        ::core::result::Result::Ok(())
    }
}
fn run_fixture(name: &str) {
    let fixtures_root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("fixtures");
    let input_dir = fixtures_root.join(name).join("input");
    let expected_dir = fixtures_root.join(name).join("expected");
    assert!(input_dir.exists(), "fixture input missing: {}", input_dir.display());
    assert!(
        expected_dir.exists(), "fixture expected missing: {}", expected_dir.display()
    );
    let tempdir = tempfile::tempdir().expect("tempdir");
    copy_tree(&input_dir, tempdir.path()).expect("copy input");
    git_init_commit(tempdir.path()).expect("git init/commit");
    let bin = env!("CARGO_BIN_EXE_rudzio-migrate");
    let args_file = fixtures_root.join(name).join("args.txt");
    let stdin_file = fixtures_root.join(name).join("stdin.txt");
    let extra_args: Vec<String> = if args_file.exists() {
        fs::read_to_string(&args_file)
            .unwrap_or_default()
            .split_whitespace()
            .map(str::to_owned)
            .collect()
    } else {
        Vec::new()
    };
    let stdin_script = if stdin_file.exists() {
        fs::read_to_string(&stdin_file).unwrap_or_default()
    } else {
        format!("{ACK_PHRASE}\nn\n")
    };
    let mut cmd = Command::new(bin);
    #[allow(clippy::shadow_unrelated)]
    {
        let _c = cmd.arg("--path").arg(tempdir.path());
        for a in &extra_args {
            let _c = cmd.arg(a);
        }
        let _c = cmd.stdin(Stdio::piped());
        let _c = cmd.stdout(Stdio::piped());
        let _c = cmd.stderr(Stdio::piped());
    }
    let mut child = cmd.spawn().expect("spawn rudzio-migrate");
    child
        .stdin
        .as_mut()
        .expect("stdin")
        .write_all(stdin_script.as_bytes())
        .expect("write stdin");
    let output = child.wait_with_output().expect("wait");
    if !output.status.success() {
        panic!(
            "rudzio-migrate exited with {}\nstdout:\n{}\nstderr:\n{}", output.status,
            String::from_utf8_lossy(& output.stdout), String::from_utf8_lossy(& output
            .stderr),
        );
    }
    compare_trees(&expected_dir, tempdir.path());
}
fn copy_tree(src: &Path, dst: &Path) -> std::io::Result<()> {
    for entry in walk(src) {
        let rel = entry
            .strip_prefix(src)
            .map_err(|e| std::io::Error::other(format!("strip_prefix: {e}")))?;
        let target = dst.join(rel);
        if entry.is_dir() {
            fs::create_dir_all(&target)?;
        } else {
            if let Some(parent) = target.parent() {
                fs::create_dir_all(parent)?;
            }
            let _bytes = fs::copy(&entry, &target)?;
        }
    }
    Ok(())
}
fn walk(root: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    if !root.is_dir() {
        return out;
    }
    let mut stack = vec![root.to_path_buf()];
    while let Some(dir) = stack.pop() {
        let Ok(rd) = fs::read_dir(&dir) else { continue };
        for entry in rd.flatten() {
            let p = entry.path();
            if p.is_dir() {
                stack.push(p);
            } else {
                out.push(p);
            }
        }
    }
    out.sort();
    out
}
fn git_init_commit(dir: &Path) -> std::io::Result<()> {
    run_git(dir, &["init", "-q"])?;
    run_git(dir, &["add", "."])?;
    run_git(
        dir,
        &[
            "-c",
            "user.email=test@example.com",
            "-c",
            "user.name=test",
            "commit",
            "-q",
            "-m",
            "init",
        ],
    )?;
    Ok(())
}
fn run_git(dir: &Path, args: &[&str]) -> std::io::Result<()> {
    let status = Command::new("git").current_dir(dir).args(args).status()?;
    if !status.success() {
        return Err(std::io::Error::other(format!("git {args:?} failed")));
    }
    Ok(())
}
/// Build a throwaway single-crate layout with a trivial `src/lib.rs`
/// and a `rust-toolchain.toml` pinning the workspace's toolchain. Used
/// by the negative-path tests (`dirty_tree_refusal`,
/// `wrong_acknowledgement`) where the crate contents don't matter —
/// only the preflight flow does.
fn setup_minimal_lib_crate(path: &Path, package_name: &str) -> std::io::Result<()> {
    fs::create_dir_all(path.join("src"))?;
    fs::write(
        path.join("Cargo.toml"),
        format!(
            "[package]\nname = \"{package_name}\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n[dependencies]\n"
        ),
    )?;
    fs::write(path.join("rust-toolchain.toml"), "[toolchain]\nchannel = \"1.95.0\"\n")?;
    fs::write(path.join("src/lib.rs"), "pub fn noop() {}\n")
}
/// Run the `rudzio-migrate` binary against `path` with the given extra
/// args and stdin input, and return the captured `Output`. Does not
/// panic on non-zero exit — callers inspect `output.status` and
/// stdout/stderr to assert the expected failure mode.
fn run_migrate(
    path: &Path,
    extra_args: &[&str],
    stdin_input: &str,
) -> std::io::Result<std::process::Output> {
    let bin = env!("CARGO_BIN_EXE_rudzio-migrate");
    let mut cmd = Command::new(bin);
    #[allow(clippy::shadow_unrelated)]
    {
        let _c = cmd.arg("--path").arg(path);
        for a in extra_args {
            let _c = cmd.arg(a);
        }
        let _c = cmd.stdin(Stdio::piped());
        let _c = cmd.stdout(Stdio::piped());
        let _c = cmd.stderr(Stdio::piped());
    }
    let mut child = cmd.spawn()?;
    if let Some(stdin) = child.stdin.as_mut() {
        stdin.write_all(stdin_input.as_bytes())?;
    }
    child.wait_with_output()
}
fn compare_trees(expected: &Path, actual: &Path) {
    let mut diffs = Vec::new();
    for entry in walk(expected) {
        let rel = entry.strip_prefix(expected).expect("strip");
        let actual_path = actual.join(rel);
        let expected_bytes = fs::read(&entry).unwrap_or_default();
        let actual_bytes = fs::read(&actual_path).unwrap_or_default();
        if expected_bytes != actual_bytes {
            diffs.push((rel.to_path_buf(), expected_bytes, actual_bytes));
        }
    }
    if !diffs.is_empty() {
        let mut msg = String::from("fixture output differs from expected:\n");
        for (rel, exp, act) in &diffs {
            msg.push_str(
                &format!(
                    "--- {} (expected vs actual) ---\nEXPECTED:\n{}\nACTUAL:\n{}\n", rel
                    .display(), String::from_utf8_lossy(exp),
                    String::from_utf8_lossy(act),
                ),
            );
        }
        panic!("{msg}");
    }
}
#[::rudzio::main]
fn main() {}
