//! Rudzio test runner entry. Generated by rudzio-migrate.
//!
//! All `#[rudzio::suite(...)]` blocks registered at the lib's
//! non-test scope reach this binary via the `use <crate> as _;`
//! below. Suite blocks gated by `#[cfg(test)]` inside the lib
//! don't — they require `#[path]` aggregation here with the lib's
//! `crate::<mod>::...` paths re-exported.

use rudzio_migrate as _;

#[rudzio::main]
fn main() {}
