//! Rudzio test runner entry. Generated by rudzio-migrate.
//!
//! Each `mod X;` declared at the crate root of `src/lib.rs` is
//! pulled in below via `#[path]`. That recompiles the files INTO
//! this test binary with `cfg(test)` active, so `#[rudzio::suite]`
//! blocks inside `#[cfg(test)] mod tests { ... }` register their
//! `linkme::distributed_slice` entries into this binary's slice.
//! The runner then finds them.
//!
//! Because the includes mirror the lib's module tree, any
//! `use crate::<mod>::...` paths inside the included files resolve
//! to the equivalent module in this binary.

// Every lib `pub mod X;` is `mod X;` here — items that are `pub`
// inside those files aren't reachable outside this test binary,
// which trips `unreachable_pub`; and items only used by the
// non-test code paths look unused when only the `#[cfg(test)]`
// modules run. Both lints are legitimate in a normal lib but
// meaningless for a test-binary recompile.
#![allow(
    unreachable_pub,
    dead_code,
    reason = "test binary is a recompile of the lib; visibility and usage lints don't apply here"
)]

#[path = "../src/backup.rs"]
mod backup;

#[path = "../src/cli.rs"]
mod cli;

#[path = "../src/detect.rs"]
mod detect;

#[path = "../src/discovery.rs"]
mod discovery;

#[path = "../src/emit.rs"]
mod emit;

#[path = "../src/manifest.rs"]
mod manifest;

#[path = "../src/phrase.rs"]
mod phrase;

#[path = "../src/preflight.rs"]
mod preflight;

#[path = "../src/report.rs"]
mod report;

#[path = "../src/rewrite.rs"]
mod rewrite;

#[path = "../src/runner_scaffold.rs"]
mod runner_scaffold;

#[path = "../src/test_context.rs"]
mod test_context;

#[path = "../src/run.rs"]
mod run;

mod golden;

#[rudzio::main]
fn main() {}
