use std::fmt;

use crate::suite::{RuntimeGroupKey, RuntimeGroupOwner, TestRunFn};

/// A self-contained, type-erased descriptor for a single test.
///
/// Generated by `#[rudzio::suite]` and registered in the process-wide linkme
/// slice so that `rudzio::run()` can discover all tests at process startup
/// without needing to know about any module structure.
///
/// The lifecycle (runtime + suite setup/teardown, dispatching test bodies,
/// timing out, cancelling) lives in the per-`(R, S)` [`RuntimeGroupOwner`].
/// Tokens that share the same `runtime_group_key` are coalesced at startup
/// and run together on one OS thread, one runtime, one suite instance —
/// even when emitted by different `#[rudzio::suite]` blocks.
///
/// `run_test` is a per-test HRTB unsafe fn pointer the owner invokes with
/// pointers to its concrete runtime and suite; the macro guarantees the
/// pointed-to types match the owner's `group_key`.
#[derive(Clone, Copy)]
#[non_exhaustive]
pub struct Token {
    /// Source file path, used to sort tests into stable source order.
    pub file: &'static str,
    /// `true` when the test was declared with
    /// `#[rudzio::test(benchmark = ...)]`. Runner-level filter: in
    /// [`crate::config::BenchMode::Skip`] mode the runner ignores these
    /// tests before dispatch; in [`crate::config::BenchMode::Full`] mode
    /// the dispatch fn runs them through their strategy.
    pub has_benchmark: bool,
    /// Reason string supplied via `#[ignore = "…"]`; empty when none.
    pub ignore_reason: &'static str,
    /// `true` when the test was declared with `#[ignore]` or
    /// `#[ignore = "…"]`.
    pub ignored: bool,
    /// Source line number, used to sort tests into stable source order.
    pub line: u32,
    /// Colon-delimited module path from the test's defining crate root to
    /// the module that contains the `#[rudzio::test]` function (the value
    /// of `::core::module_path!()` at the expansion site). The runner
    /// runs this through [`normalize_module_path`](crate::normalize_module_path)
    /// to drop autogenerated segments (the leading crate name, the
    /// aggregator's `tests::` wrapper, and any `main` shim segment),
    /// joins the result with [`Self::name`] via
    /// [`qualified_test_name`](crate::qualified_test_name) for display,
    /// and the positional-filter / `--skip` substring-match runs against
    /// that same display form — so any fragment a user can copy out of
    /// the runner's output is a valid filter.
    pub module_path: &'static str,
    /// Source-level test function name (the `fn` identifier, not the
    /// fully-qualified path). Joined with [`Self::module_path`] to form
    /// the display label.
    pub name: &'static str,
    /// Per-test dispatch fn — see [`TestRunFn`] for the safety contract.
    pub run_test: TestRunFn,
    /// Compile-time hash of `(runtime_path, suite_path)`. Tokens sharing
    /// this key run on one shared runtime + suite.
    pub runtime_group_key: RuntimeGroupKey,
    /// Pointer to a [`RuntimeGroupOwner`] for this `(R, S)` pair. Multiple
    /// tokens with the same `runtime_group_key` may carry distinct (but
    /// functionally equivalent) owner pointers; the runner picks any one.
    /// The runtime's display name comes from
    /// [`Runtime::name`](crate::runtime::Runtime::name), available only
    /// after the group thread constructs the runtime instance.
    pub runtime_group_owner: &'static dyn RuntimeGroupOwner,
}

/// Source-location metadata block — file, line, module path, and test
/// fn name. Bundled so [`Token::new`] takes one struct instead of
/// four positional args, sidestepping `clippy::too_many_arguments`.
#[derive(Clone, Copy, Debug)]
#[doc(hidden)]
#[non_exhaustive]
pub struct Source {
    /// See [`Token::file`].
    pub file: &'static str,
    /// See [`Token::line`].
    pub line: u32,
    /// See [`Token::module_path`].
    pub module_path: &'static str,
    /// See [`Token::name`].
    pub name: &'static str,
}

impl Source {
    /// Pack the four source-location fields. Macro-only.
    #[doc(hidden)]
    #[inline]
    #[must_use]
    pub const fn new(
        file: &'static str,
        line: u32,
        module_path: &'static str,
        name: &'static str,
    ) -> Self {
        Self {
            file,
            line,
            module_path,
            name,
        }
    }
}

/// `#[ignore]` / `#[rudzio::test(benchmark = …)]` attributes block.
#[derive(Clone, Copy, Debug)]
#[doc(hidden)]
#[non_exhaustive]
pub struct Attrs {
    /// See [`Token::has_benchmark`].
    pub has_benchmark: bool,
    /// See [`Token::ignore_reason`].
    pub ignore_reason: &'static str,
    /// See [`Token::ignored`].
    pub ignored: bool,
}

impl Attrs {
    /// Pack the three attribute-derived fields. Macro-only.
    #[doc(hidden)]
    #[inline]
    #[must_use]
    pub const fn new(has_benchmark: bool, ignore_reason: &'static str, ignored: bool) -> Self {
        Self {
            has_benchmark,
            ignore_reason,
            ignored,
        }
    }
}

/// Runtime-group dispatch wiring — the `(R, S)` group key, its owner,
/// and the per-test dispatch fn pointer.
#[derive(Clone, Copy)]
#[doc(hidden)]
#[non_exhaustive]
pub struct Dispatch {
    /// See [`Token::run_test`].
    pub run_test: TestRunFn,
    /// See [`Token::runtime_group_key`].
    pub runtime_group_key: RuntimeGroupKey,
    /// See [`Token::runtime_group_owner`].
    pub runtime_group_owner: &'static dyn RuntimeGroupOwner,
}

impl Dispatch {
    /// Pack the three dispatch fields. Macro-only.
    #[doc(hidden)]
    #[inline]
    #[must_use]
    pub const fn new(
        run_test: TestRunFn,
        runtime_group_key: RuntimeGroupKey,
        runtime_group_owner: &'static dyn RuntimeGroupOwner,
    ) -> Self {
        Self {
            run_test,
            runtime_group_key,
            runtime_group_owner,
        }
    }
}

impl fmt::Debug for Dispatch {
    #[inline]
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Dispatch")
            .field("runtime_group_key", &self.runtime_group_key)
            .finish_non_exhaustive()
    }
}

impl Token {
    /// Construct a `Token` from its three sub-bundles.
    /// Macro-generated code calls this so the struct can stay
    /// `#[non_exhaustive]`.
    #[doc(hidden)]
    #[inline]
    #[must_use]
    pub const fn new(source: Source, attrs: Attrs, dispatch: Dispatch) -> Self {
        let Source {
            file,
            line,
            module_path,
            name,
        } = source;
        let Attrs {
            has_benchmark,
            ignore_reason,
            ignored,
        } = attrs;
        let Dispatch {
            run_test,
            runtime_group_key,
            runtime_group_owner,
        } = dispatch;
        Self {
            file,
            has_benchmark,
            ignore_reason,
            ignored,
            line,
            module_path,
            name,
            run_test,
            runtime_group_key,
            runtime_group_owner,
        }
    }
}

impl fmt::Debug for Token {
    #[inline]
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Token")
            .field("name", &self.name)
            .field("module_path", &self.module_path)
            .field("ignored", &self.ignored)
            .field("ignore_reason", &self.ignore_reason)
            .field("has_benchmark", &self.has_benchmark)
            .field("file", &self.file)
            .field("line", &self.line)
            .field("runtime_group_key", &self.runtime_group_key)
            .finish_non_exhaustive()
    }
}

#[::linkme::distributed_slice]
#[doc(hidden)]
pub static TEST_TOKENS: [Token] = [..];
