use std::fmt;

use crate::suite::{RuntimeGroupKey, RuntimeGroupOwner, TestRunFn};

/// A self-contained, type-erased descriptor for a single test.
///
/// Generated by `#[rudzio::suite]` and registered in the process-wide linkme
/// slice so that `rudzio::run()` can discover all tests at process startup
/// without needing to know about any module structure.
///
/// The lifecycle (runtime + suite setup/teardown, dispatching test bodies,
/// timing out, cancelling) lives in the per-`(R, S)` [`RuntimeGroupOwner`].
/// Tokens that share the same `runtime_group_key` are coalesced at startup
/// and run together on one OS thread, one runtime, one suite instance —
/// even when emitted by different `#[rudzio::suite]` blocks.
///
/// `run_test` is a per-test HRTB unsafe fn pointer the owner invokes with
/// pointers to its concrete runtime and suite; the macro guarantees the
/// pointed-to types match the owner's `group_key`.
#[derive(Clone, Copy)]
pub struct TestToken {
    pub name: &'static str,
    pub ignored: bool,
    pub ignore_reason: &'static str,
    /// `true` when the test was declared with
    /// `#[rudzio::test(benchmark = ...)]`. Runner-level filter: in
    /// [`crate::config::BenchMode::Skip`] mode the runner ignores these
    /// tests before dispatch; in [`crate::config::BenchMode::Full`] mode
    /// the dispatch fn runs them through their strategy.
    pub has_benchmark: bool,
    /// Source file path, used to sort tests into stable source order.
    pub file: &'static str,
    /// Source line number, used to sort tests into stable source order.
    pub line: u32,
    /// Compile-time hash of `(runtime_path, suite_path)`. Tokens sharing
    /// this key run on one shared runtime + suite.
    pub runtime_group_key: RuntimeGroupKey,
    /// Pointer to a [`RuntimeGroupOwner`] for this `(R, S)` pair. Multiple
    /// tokens with the same `runtime_group_key` may carry distinct (but
    /// functionally equivalent) owner pointers; the runner picks any one.
    /// The runtime's display name comes from
    /// [`Runtime::name`](crate::runtime::Runtime::name), available only
    /// after the group thread constructs the runtime instance.
    pub runtime_group_owner: &'static dyn RuntimeGroupOwner,
    /// Per-test dispatch fn — see [`TestRunFn`] for the safety contract.
    pub run_test: TestRunFn,
}

impl fmt::Debug for TestToken {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("TestToken")
            .field("name", &self.name)
            .field("ignored", &self.ignored)
            .field("ignore_reason", &self.ignore_reason)
            .field("has_benchmark", &self.has_benchmark)
            .field("file", &self.file)
            .field("line", &self.line)
            .field("runtime_group_key", &self.runtime_group_key)
            .finish_non_exhaustive()
    }
}

#[::linkme::distributed_slice]
#[doc(hidden)]
pub static TEST_TOKENS: [TestToken] = [..];
