use std::fmt;

use crate::suite::SuiteRunner;

/// A self-contained, type-erased descriptor for a single test.
///
/// Generated by `#[rudzio::suite]` and registered in the global linkme slice
/// so that `rudzio::run()` can discover all tests at process startup without
/// needing to know about any module structure.
///
/// All per-suite orchestration (creating the runtime, setting up the global
/// context, dispatching the test body, tearing down) lives in
/// [`SuiteRunner`]. Every token belonging to the same `#[rudzio::suite]`
/// invocation points at the same `&'static dyn SuiteRunner`; the runner uses
/// `suite_local_index` to pick the correct test body inside that suite.
#[derive(Clone, Copy)]
pub struct TestToken {
    pub name: &'static str,
    pub ignored: bool,
    pub ignore_reason: &'static str,
    /// Source file path, used to sort tests into stable source order.
    pub file: &'static str,
    /// Source line number, used to sort tests into stable source order.
    pub line: u32,
    /// Display name of the runtime constructor for this suite (e.g.
    /// `"Multithread::new"`). Mirrors `suite_runner.runtime_name()` but is
    /// available without an indirection so the runner can render listing
    /// output without instantiating anything.
    pub runtime_name: &'static str,
    /// Pointer to the per-suite orchestrator.
    pub suite_runner: &'static dyn SuiteRunner,
    /// Index into the suite's internal test dispatch table.
    pub suite_local_index: usize,
}

impl fmt::Debug for TestToken {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("TestToken")
            .field("name", &self.name)
            .field("ignored", &self.ignored)
            .field("ignore_reason", &self.ignore_reason)
            .field("file", &self.file)
            .field("line", &self.line)
            .field("runtime_name", &self.runtime_name)
            .field("suite_local_index", &self.suite_local_index)
            .finish_non_exhaustive()
    }
}

#[::linkme::distributed_slice]
#[doc(hidden)]
pub static TEST_TOKENS: [TestToken] = [..];
