use tests_only_flag::ident;
#[cfg(any(test, rudzio_test))]
#[allow(non_snake_case, reason = "generated by rudzio-migrate")]
#[::rudzio::suite(
    [(
        runtime = ::rudzio::runtime::tokio::Multithread::new,
        suite = ::rudzio::common::context::Suite,
        test = ::rudzio::common::context::Test,
    ),
    ]
)]
mod tests {
    use super::*;
    /* pre-migration (rudzio-migrate):
    #[test]
    fn integration_passes() {
        assert_eq!(ident("hi"), "hi");
    }
    */
    #[::rudzio::test]
    async fn integration_passes() -> ::anyhow::Result<()> {
        assert_eq!(ident("hi"), "hi");
        ::core::result::Result::Ok(())
    }
}
#[::rudzio::main]
fn main() {}
